---

before_script:
  - packer version

stages:
  - validate
  - inspect
  - build

validate-packerfile:
  stage: validate
  script:
    - packer validate ps-vagabond-oel.json

inspect-packerfile:
  stage: inspect
  script:
    - packer inspect ps-vagabond-oel.json

build-oel-hyperv:
  stage: build
  variables:
    PACKER_BASE: 'C:\psoft\packer_base'
  script:
    - packer build -force -only=hyperv ps-vagabond-oel.json
  when: manual
  tags:
    - windows
    - hyperv

build-oel-virtualbox:
  stage: build
  variables:
    PACKER_BASE: 'D:\packer_base'
  script:
    - packer build -force -only=virtualbox ps-vagabond-oel.json
  when: manual
  tags:
    - windows
    - virtualbox

build-windows-hyperv:
  stage: build
  variables:
    PACKER_BASE: 'C:\psoft\packer_base'
  script:
    - packer build -force -only=hyperv ps-vagabond-win.json
  when: manual
  tags:
    - windows
    - hyperv

build-windows-virtualbox:
  stage: build
  variables:
    PACKER_BASE: 'D:\packer_base'
  script:
    - packer build -force -only=virtualbox ps-vagabond-win.json
  when: manual
  tags:
    - windows
    - virtualbox
