---

before_script:
  - packer version

stages:
  - validate
  - inspect
  - build

validate-packerfile:
  stage: validate
  script:
    - packer validate ps-vagabond-oel.json

inspect-packerfile:
  stage: inspect
  script:
    - packer inspect ps-vagabond-oel.json

build-oel-hyperv:
  stage: build
  script:
    - packer build -only=hyperv ps-vagabond-oel.json
  when: manual
  tags:
    - windows
    - hyperv
